# Reference pm4py Code XES to DF

## Converting XES to pandas data frame

In [2]:
from pm4py.objects.log.importer.xes import importer as xes_importer
import pandas as pd
from pm4py.objects.conversion.log import converter as log_converter

variant = xes_importer.Variants.ITERPARSE
parameters = {variant.value.Parameters.TIMESTAMP_SORT: True}
log = xes_importer.apply('running-example.xes',
                         variant=variant, parameters=parameters)
#parameters = {log_converter.Variants.TO_DATA_FRAME.value.Parameters.CASE_ID_KEY: 'case:'}
df_event_log = log_converter.apply(log, variant=log_converter.Variants.TO_DATA_FRAME)
df_event_log

HBox(children=(FloatProgress(value=0.0, description='parsing log, completed traces :: ', max=6.0, style=Progreâ€¦

,concept:name,org:resource,time:timestamp,Activity,Resource,Costs,case:concept:name,case:creator
0,register request,Pete,2010-12-30 11:02:00+01:00,register request,Pete,50,1,Fluxicon Nitro
1,examine thoroughly,Sue,2010-12-31 10:06:00+01:00,examine thoroughly,Sue,400,1,Fluxicon Nitro
2,check ticket,Mike,2011-01-05 15:12:00+01:00,check ticket,Mike,100,1,Fluxicon Nitro
3,decide,Sara,2011-01-06 11:18:00+01:00,decide,Sara,200,1,Fluxicon Nitro
4,reject request,Pete,2011-01-07 14:24:00+01:00,reject request,Pete,200,1,Fluxicon Nitro
5,register request,Mike,2010-12-30 11:32:00+01:00,register request,Mike,50,2,Fluxicon Nitro
6,check ticket,Mike,2010-12-30 12:12:00+01:00,check ticket,Mike,100,2,Fluxicon Nitro
7,examine casually,Sean,2010-12-30 14:16:00+01:00,examine casually,Sean,400,2,Fluxicon Nitro
8,decide,Sara,2011-01-05 11:22:00+01:00,decide,Sara,200,2,Fluxicon Nitro
9,pay compensation,Ellen,2011-01-08 12:05:00+01:00,pay compensation,Ellen,200,2,Fluxicon Nitro
10,register request,Pete,2010-12-30 14:32:00+01:00,register request,Pete,50,3,Fluxicon Nitro
11,examine casually,Mike,2010-12-30 15:06:00+01:00,examine casually,Mike,400,3,Fluxicon Nitro
12,check ticket,Ellen,2010-12-30 16:34:00+01:00,check ticket,Ellen,100,3,Fluxicon Nitro
13,decide,Sara,2011-01-06 09:18:00+01:00,decide,Sara,200,3,Fluxicon Nitro
14,reinitiate request,Sara,2011-01-06 12:18:00+01:00,reinitiate request,Sara,200,3,Fluxicon Nitro
15,examine thoroughly,Sean,2011-01-06 13:06:00+01:00,examine thoroughly,Sean,400,3,Fluxicon Nitro
16,check ticket,Pete,2011-01-08 11:43:00+01:00,check ticket,Pete,100,3,Fluxicon Nitro
17,decide,Sara,2011-01-09 09:55:00+01:00,decide,Sara,200,3,Fluxicon Nitro
18,pay compensation,Ellen,2011-01-15 10:45:00+01:00,pay compensation,Ellen,200,3,Fluxicon Nitro
19,register request,Ellen,2011-01-06 09:02:00+01:00,register request,Ellen,50,5,Fluxicon Nitro
20,examine casually,Mike,2011-01-07 10:16:00+01:00,examine casually,Mike,400,5,Fluxicon Nitro
21,check ticket,Pete,2011-01-08 11:22:00+01:00,check ticket,Pete,100,5,Fluxicon Nitro
22,decide,Sara,2011-01-10 13:28:00+01:00,decide,Sara,200,5,Fluxicon Nitro
23,reinitiate request,Sara,2011-01-11 16:18:00+01:00,reinitiate request,Sara,200,5,Fluxicon Nitro
24,check ticket,Ellen,2011-01-14 14:33:00+01:00,check ticket,Ellen,100,5,Fluxicon Nitro
25,examine casually,Mike,2011-01-16 15:50:00+01:00,examine casually,Mike,400,5,Fluxicon Nitro
26,decide,Sara,2011-01-19 11:18:00+01:00,decide,Sara,200,5,Fluxicon Nitro
27,reinitiate request,Sara,2011-01-20 12:48:00+01:00,reinitiate request,Sara,200,5,Fluxicon Nitro
28,examine casually,Sue,2011-01-21 09:06:00+01:00,examine casually,Sue,400,5,Fluxicon Nitro
29,check ticket,Pete,2011-01-21 11:34:00+01:00,check ticket,Pete,100,5,Fluxicon Nitro
30,decide,Sara,2011-01-23 13:12:00+01:00,decide,Sara,200,5,Fluxicon Nitro
31,reject request,Mike,2011-01-24 14:56:00+01:00,reject request,Mike,200,5,Fluxicon Nitro
32,register request,Mike,2011-01-06 15:02:00+01:00,register request,Mike,50,6,Fluxicon Nitro
33,examine casually,Ellen,2011-01-06 16:06:00+01:00,examine casually,Ellen,400,6,Fluxicon Nitro
34,check ticket,Mike,2011-01-07 16:22:00+01:00,check ticket,Mike,100,6,Fluxicon Nitro
35,decide,Sara,2011-01-07 16:52:00+01:00,decide,Sara,200,6,Fluxicon Nitro
36,pay compensation,Mike,2011-01-16 11:47:00+01:00,pay compensation,Mike,200,6,Fluxicon Nitro
37,register request,Pete,2011-01-06 15:02:00+01:00,register request,Pete,50,4,Fluxicon Nitro
38,check ticket,Mike,2011-01-07 12:06:00+01:00,check ticket,Mike,100,4,Fluxicon Nitro
39,examine thoroughly,Sean,2011-01-08 14:43:00+01:00,examine thoroughly,Sean,400,4,Fluxicon Nitro
40,decide,Sara,2011-01-09 12:02:00+01:00,decide,Sara,200,4,Fluxicon Nitro
41,reject request,Ellen,2011-01-12 15:44:00+01:00,reject request,Ellen,200,4,Fluxicon Nitro

## Event Log metadata

log level data and meta data only available as a pm4py event log object

In [3]:
print(log.attributes)
print(log.classifiers)
print(log.omni_present)

{'creator': 'Fluxicon Nitro'}
{'Activity': ['Activity'], 'activity classifier': ['Activity']}
{'trace': {'concept:name': 'name'}, 'event': {'concept:name': 'name', 'org:resource': 'resource', 'time:timestamp': datetime.datetime(2011, 4, 13, 14, 2, 31, 199000, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))), 'Activity': 'string', 'Resource': 'string', 'Costs': 'string'}}

In [4]:
import os
from  pm4py.visualization.graphs.variants.dates import apply_semilogx as visualizer
visulizer. attributes=["concept:name", "org:resource", "org:group"])

AttributeError: module 'pm4py' has no attribute 'view_dotted_chart'